#!/usr/bin/env bash
set -euo pipefail

# TrustMesh testnet deployment
# Usage: ./scripts/deploy.sh [--source IDENTITY] [--network testnet]

SOURCE="${SOURCE:-trustmesh-admin}"
NETWORK="${NETWORK:-testnet}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source) SOURCE="$2"; shift 2 ;;
    --network) NETWORK="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "==> Building contracts"
stellar contract build

WASM_DIR="$ROOT/target/wasm32v1-none/release"
# Fallback for older target names
if [[ ! -d "$WASM_DIR" ]]; then
  WASM_DIR="$ROOT/target/wasm32-unknown-unknown/release"
fi

deploy_one() {
  local name="$1"
  local wasm="$WASM_DIR/${name}.wasm"
  echo "==> Deploying $name"
  stellar contract deploy \
    --wasm "$wasm" \
    --source "$SOURCE" \
    --network "$NETWORK"
}

echo "==> Ensuring identity exists"
if ! stellar keys address "$SOURCE" >/dev/null 2>&1; then
  echo "Identity '$SOURCE' not found. Create with:"
  echo "  stellar keys generate $SOURCE --network $NETWORK --fund"
  exit 1
fi

ADMIN="$(stellar keys address "$SOURCE")"
echo "Admin: $ADMIN"

ORG_REGISTRY="$(deploy_one organization_registry)"
REPUTATION="$(deploy_one reputation)"
TREASURY="$(deploy_one treasury)"
TRUST_REL="$(deploy_one trust_relationship)"
FACTORY="$(deploy_one trust_relationship_factory)"
REVIEW="$(deploy_one review_verification)"

echo "==> Initializing contracts"

stellar contract invoke --id "$ORG_REGISTRY" --source "$SOURCE" --network "$NETWORK" -- \
  initialize --admin "$ADMIN"

stellar contract invoke --id "$REPUTATION" --source "$SOURCE" --network "$NETWORK" -- \
  initialize --admin "$ADMIN"

stellar contract invoke --id "$TREASURY" --source "$SOURCE" --network "$NETWORK" -- \
  initialize --admin "$ADMIN"

stellar contract invoke --id "$TRUST_REL" --source "$SOURCE" --network "$NETWORK" -- \
  initialize --admin "$ADMIN" --factory "$FACTORY" --reputation "$REPUTATION"

stellar contract invoke --id "$FACTORY" --source "$SOURCE" --network "$NETWORK" -- \
  initialize --admin "$ADMIN" --registry "$ORG_REGISTRY" --relationship "$TRUST_REL" \
  --reputation "$REPUTATION" --treasury "$TREASURY"

stellar contract invoke --id "$REVIEW" --source "$SOURCE" --network "$NETWORK" -- \
  initialize --admin "$ADMIN" --registry "$ORG_REGISTRY" --reputation "$REPUTATION" \
  --treasury "$TREASURY"

echo "==> Authorizing cross-contract callers"

stellar contract invoke --id "$REPUTATION" --source "$SOURCE" --network "$NETWORK" -- \
  set_authorized --caller "$FACTORY" --authorized true
stellar contract invoke --id "$REPUTATION" --source "$SOURCE" --network "$NETWORK" -- \
  set_authorized --caller "$TRUST_REL" --authorized true
stellar contract invoke --id "$REPUTATION" --source "$SOURCE" --network "$NETWORK" -- \
  set_authorized --caller "$REVIEW" --authorized true

stellar contract invoke --id "$TREASURY" --source "$SOURCE" --network "$NETWORK" -- \
  set_authorized --caller "$FACTORY" --authorized true
stellar contract invoke --id "$TREASURY" --source "$SOURCE" --network "$NETWORK" -- \
  set_authorized --caller "$REVIEW" --authorized true

OUT_DIR="$ROOT/deployments"
mkdir -p "$OUT_DIR"
ENV_FILE="$OUT_DIR/testnet.env"

cat > "$ENV_FILE" <<EOF
# TrustMesh Stellar Testnet deployment
# Generated by scripts/deploy.sh

NEXT_PUBLIC_RPC_URL=https://soroban-testnet.stellar.org
NEXT_PUBLIC_HORIZON_URL=https://horizon-testnet.stellar.org
NEXT_PUBLIC_ORGANIZATION_REGISTRY_ID=$ORG_REGISTRY
NEXT_PUBLIC_REPUTATION_ID=$REPUTATION
NEXT_PUBLIC_TREASURY_ID=$TREASURY
NEXT_PUBLIC_TRUST_RELATIONSHIP_ID=$TRUST_REL
NEXT_PUBLIC_TRUST_RELATIONSHIP_FACTORY_ID=$FACTORY
NEXT_PUBLIC_REVIEW_VERIFICATION_ID=$REVIEW
EOF

cp "$ENV_FILE" "$ROOT/frontend/.env.local" 2>/dev/null || true

echo ""
echo "✅ Deployment complete"
echo "Addresses written to $ENV_FILE"
cat "$ENV_FILE"
