import type {
  ActivityEvent,
  Organization,
  Relationship,
  ReputationScore,
  Review,
} from "./types";

/** Deterministic demo dataset used when contracts are not yet configured. */
export const DEMO_ORGS: Organization[] = [
  {
    id: 1,
    owner: "GDEMOACMEAAAAAAAAAAAAAAAAMERCHANT01",
    name: "Northwind Labs",
    orgType: "Startup",
    metadataUri: "ipfs://northwind",
    verified: true,
    registeredAt: Math.floor(Date.now() / 1000) - 86400 * 40,
    vendorCount: 3,
    trustScore: 842,
  },
  {
    id: 2,
    owner: "GDEMOAGENCYAAAAAAAAAAAAAAASERVICES02",
    name: "Harbor Agency",
    orgType: "Agency",
    metadataUri: "ipfs://harbor",
    verified: true,
    registeredAt: Math.floor(Date.now() / 1000) - 86400 * 28,
    vendorCount: 1,
    trustScore: 710,
  },
  {
    id: 3,
    owner: "GDEMOFREELANCEAAAAAAAAAAAADEVELPR03",
    name: "PixelForge Studio",
    orgType: "Freelancer",
    metadataUri: "ipfs://pixelforge",
    verified: false,
    registeredAt: Math.floor(Date.now() / 1000) - 86400 * 12,
    vendorCount: 0,
    trustScore: 465,
  },
  {
    id: 4,
    owner: "GDEMOVENDORAAAAAAAAAAAAAAAASUPPLY04",
    name: "Atlas Vendor Co",
    orgType: "Vendor",
    metadataUri: "ipfs://atlas",
    verified: true,
    registeredAt: Math.floor(Date.now() / 1000) - 86400 * 55,
    vendorCount: 8,
    trustScore: 901,
  },
];

export const DEMO_RELATIONSHIPS: Relationship[] = [
  {
    id: 1,
    partyA: DEMO_ORGS[0].owner,
    partyB: DEMO_ORGS[1].owner,
    orgA: 1,
    orgB: 2,
    title: "Brand site rebuild",
    status: "Completed",
    aAccepted: true,
    bAccepted: true,
    aCompleted: true,
    bCompleted: true,
    createdAt: Math.floor(Date.now() / 1000) - 86400 * 20,
    completedAt: Math.floor(Date.now() / 1000) - 86400 * 5,
    disputeReason: "",
    qualityScore: 92,
  },
  {
    id: 2,
    partyA: DEMO_ORGS[1].owner,
    partyB: DEMO_ORGS[3].owner,
    orgA: 2,
    orgB: 4,
    title: "Print & packaging supply",
    status: "Active",
    aAccepted: true,
    bAccepted: true,
    aCompleted: false,
    bCompleted: false,
    createdAt: Math.floor(Date.now() / 1000) - 86400 * 8,
    completedAt: 0,
    disputeReason: "",
    qualityScore: 0,
  },
  {
    id: 3,
    partyA: DEMO_ORGS[0].owner,
    partyB: DEMO_ORGS[2].owner,
    orgA: 1,
    orgB: 3,
    title: "Product illustration pack",
    status: "Disputed",
    aAccepted: true,
    bAccepted: true,
    aCompleted: false,
    bCompleted: false,
    createdAt: Math.floor(Date.now() / 1000) - 86400 * 6,
    completedAt: 0,
    disputeReason: "Delivery scope mismatch",
    qualityScore: 0,
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: 1,
    reviewer: DEMO_ORGS[0].owner,
    reviewerOrg: 1,
    revieweeOrg: 2,
    relationshipId: 1,
    rating: 5,
    commentHash: "sha256:harbor-excellent-delivery",
    status: "Verified",
    submittedAt: Math.floor(Date.now() / 1000) - 86400 * 4,
    verifiedAt: Math.floor(Date.now() / 1000) - 86400 * 3,
  },
  {
    id: 2,
    reviewer: DEMO_ORGS[1].owner,
    reviewerOrg: 2,
    revieweeOrg: 1,
    relationshipId: 1,
    rating: 4,
    commentHash: "sha256:northwind-clear-briefs",
    status: "Verified",
    submittedAt: Math.floor(Date.now() / 1000) - 86400 * 4,
    verifiedAt: Math.floor(Date.now() / 1000) - 86400 * 3,
  },
  {
    id: 3,
    reviewer: DEMO_ORGS[1].owner,
    reviewerOrg: 2,
    revieweeOrg: 4,
    relationshipId: 2,
    rating: 5,
    commentHash: "sha256:atlas-on-time-supply",
    status: "Submitted",
    submittedAt: Math.floor(Date.now() / 1000) - 3600 * 6,
    verifiedAt: 0,
  },
];

export const DEMO_REPUTATION: Record<number, ReputationScore> = {
  1: {
    orgId: 1,
    trustScore: 842,
    completedRelationships: 12,
    verifiedReviews: 18,
    averageRatingBps: 460,
    disputesOpened: 1,
    disputesLost: 0,
    lastUpdated: Math.floor(Date.now() / 1000) - 3600,
  },
  2: {
    orgId: 2,
    trustScore: 710,
    completedRelationships: 9,
    verifiedReviews: 11,
    averageRatingBps: 440,
    disputesOpened: 2,
    disputesLost: 1,
    lastUpdated: Math.floor(Date.now() / 1000) - 7200,
  },
  3: {
    orgId: 3,
    trustScore: 465,
    completedRelationships: 3,
    verifiedReviews: 4,
    averageRatingBps: 390,
    disputesOpened: 1,
    disputesLost: 1,
    lastUpdated: Math.floor(Date.now() / 1000) - 86400,
  },
  4: {
    orgId: 4,
    trustScore: 901,
    completedRelationships: 24,
    verifiedReviews: 31,
    averageRatingBps: 480,
    disputesOpened: 0,
    disputesLost: 0,
    lastUpdated: Math.floor(Date.now() / 1000) - 1800,
  },
};

export const DEMO_ACTIVITY: ActivityEvent[] = [
  {
    id: "e1",
    type: "OrganizationVerified",
    title: "Organization verified",
    description: "Atlas Vendor Co received platform verification",
    timestamp: Math.floor(Date.now() / 1000) - 900,
  },
  {
    id: "e2",
    type: "ReviewSubmitted",
    title: "Review submitted",
    description: "Harbor Agency rated Atlas Vendor Co ★5",
    timestamp: Math.floor(Date.now() / 1000) - 3600 * 6,
  },
  {
    id: "e3",
    type: "DisputeOpened",
    title: "Dispute opened",
    description: "Product illustration pack — delivery scope mismatch",
    timestamp: Math.floor(Date.now() / 1000) - 86400 * 2,
  },
  {
    id: "e4",
    type: "RelationshipCompleted",
    title: "Relationship completed",
    description: "Brand site rebuild closed at quality 92",
    timestamp: Math.floor(Date.now() / 1000) - 86400 * 5,
  },
  {
    id: "e5",
    type: "ReputationUpdated",
    title: "Reputation updated",
    description: "Northwind Labs trust score → 842",
    timestamp: Math.floor(Date.now() / 1000) - 86400 * 5,
  },
  {
    id: "e6",
    type: "RelationshipCreated",
    title: "Relationship created",
    description: "Print & packaging supply between Harbor and Atlas",
    timestamp: Math.floor(Date.now() / 1000) - 86400 * 8,
  },
  {
    id: "e7",
    type: "OrganizationRegistered",
    title: "Organization registered",
    description: "PixelForge Studio joined TrustMesh",
    timestamp: Math.floor(Date.now() / 1000) - 86400 * 12,
  },
];
